// steps/selectTopic.js

// The list of topics (Cleaned: no numbers)
const topicsList = [
"Architect - CAD Block Library (Residential Furniture)",
"HR Manager - New Hire Onboarding Checklist",
"Wedding Photographer - \"Golden Hour\" Lightroom Preset Pack",
"Python Developer - Web Scraper Script for Real Estate Data",
"Event Planner - Run-of-Show Template for Conferences",
"Nutritionist - 7-Day Anti-Inflammatory Meal Plan PDF",
"Real Estate Agent - First-Time Homebuyer Closing Guide",
"Graphic Designer - Minimalist Font Pairing Guide",
"ESL Teacher - IELTS Vocabulary Flashcards (Anki Deck)",
"Project Manager - Notion Project Dashboard Template",
"Personal Trainer - 12-Week Hypertrophy Excel Tracker",
"Interior Designer - \"Modern Farmhouse\" Mood Board Template",
"Music Producer - Lo-Fi Drum Sample Pack",
"Legal Consultant - Freelance Service Agreement Boilerplate",
"Etsy Seller - Inventory & Profit Tracker Spreadsheet",
"Social Media Manager - 30-Day Content Calendar Template",
"3D Artist - Blender Material Library (Metals)",
"Airbnb Host - Guest Welcome Guide PDF Template",
"Copywriter - \"About Page\" Fill-in-the-Blank Framework",
"Excel Expert - Debt Payoff Calculator with Visualizations",
"Makeup Artist - Bridal Makeup Kit Checklist",
"Videographer - Premiere Pro Color Grading LUTs",
"Webflow Developer - \"Agency Portfolio\" Cloneable Template",
"Kindergarten Teacher - Printable Alphabet Tracing Worksheets",
"SEO Specialist - Technical Audit Checklist for E-commerce",
"Fiction Writer - Character Development Scrivener Template",
"Calligrapher - Procreate Brush Set (Copperplate)",
"Travel Blogger - \"Packing for Europe\" PDF Checklist",
"Data Analyst - SQL Query Snippets for Common KPIs",
"Garden Designer - Companion Planting Chart for Zone 7",
"Virtual Assistant - Email Inbox Management SOP",
"Wedding Planner - Budget Allocation Spreadsheet",
"Flutter Developer - Pre-built Authentication UI Kit",
"Guitar Teacher - \"Beginner Chords\" PDF Tablature",
"Executive Assistant - Travel Itinerary Template for executives",
"Podcaster - Guest Outreach Email Scripts",
"Accountant - Small Business Tax Deduction Cheat Sheet",
"Dog Trainer - \"Puppy's First Month\" Training Schedule",
"UX Researcher - User Interview Question Bank",
"Notion Consultant - \"Second Brain\" Life OS Template",
"Fashion Designer - Tech Pack Template for Manufacturers",
"Game Developer - Unity 2D Sprite Asset Pack (Forest)",
"Email Marketer - Abandoned Cart Email Sequence Scripts",
"Knitting Enthusiast - \"Chunky Scarf\" Knitting Pattern PDF",
"Life Coach - \"Core Values\" Discovery Worksheet",
"DevOps Engineer - Docker Compose Config for LAMP Stack",
"Drone Pilot - Aerial Photography Shot List",
"Grant Writer - Non-Profit Grant Proposal Template",
"Speech Therapist - Articulation Practice Cards (Printable)",
"Home Organizer - Pantry Organization Label Templates",
"PPC Specialist - Google Ads Negative Keyword List (Universal)",
"Yoga Instructor - 20-Minute Morning Flow Sequence PDF",
"Indie Author - Kindle Formatting HTML Template",
"Minecraft Server Admin - Custom Config File for Modpack",
"Wedding Officiant - Ceremony Script Templates (Non-Religious)",
"Shopify Developer - Liquid Code Snippet for \"Free Shipping Bar\"",
"Financial Advisor - Retirement Savings Projection Model",
"Baker - Sourdough Starter Maintenance Log",
"Illustrator - Vector Icon Set (Office Supplies)",
"Sales Rep - Cold Call Objection Handling Script",
"Piano Teacher - Sight Reading Practice Sheets (Level 1)",
"Cybersecurity Consultant - Personal Security Audit Checklist",
"React Native Developer - Custom Hook Library for API Calls",
"Florist - Seasonal Flower Availability Chart",
"Campground Owner - Campsite Reservation Log Excel Sheet",
"Voice Actor - Home Studio EQ Preset for Audacity",
"Bartender - \"Classic Cocktails\" Recipe Cards PDF",
"Landscaper - Lawn Care Maintenance Schedule (Seasonal)",
"Notion Creator - Student Assignment Tracker Template",
"UX Writer - Microcopy Style Guide Template",
"Tattoo Artist - Flash Art Stencil Pack (Digital)",
"Genealogy Researcher - Family Tree Organization Chart",
"3D Printer Enthusiast - Headphone Stand .STL File",
"Brand Strategist - Brand Archetype Quiz PDF",
"Wedding DJ - \"Must Play\" Reception Playlist (CSV)",
"Python Tutor - \"Python for Beginners\" Cheat Sheet",
"Airbnb Co-Host - House Cleaning Inspection Checklist",
"Recruiter - Candidate Interview Scorecard",
"Ceramics Artist - Glaze Recipe Database Spreadsheet",
"Construction Manager - Daily Site Report Template",
"Blogger - Media Kit Canva Template",
"CRM Specialist - Salesforce Dashboard Layout JSON",
"Tarot Reader - \"Daily Draw\" Journal Page PDF",
"Film Director - Storyboard Template (printable)",
"Midjourney Artist - Prompt Engineering Guide for Photorealism",
"Shopify Store Owner - Profit Margin Calculator Spreadsheet",
"Choir Director - Vocal Warm-up Exercises MP3/PDF",
"Landscape Photographer - Sky Replacement Pack (JPEGs)",
"Woodworker - Workbench Build Plans (PDF)",
"Bubble.io Developer - User Profile Page Template",
"Non-Profit Manager - Volunteer Sign-up Sheet Template",
"Sewing Pattern Maker - \"Tote Bag\" Pattern (A4 Printable)",
"Product Manager - Feature Prioritization Matrix (RICE)",
"Restaurant Owner - Food Cost Inventory Spreadsheet",
"Twitch Streamer - OBS Overlay Pack (Neon Style)",
"SAT Tutor - Math Formula Memorization Sheet",
"Hiking Guide - \"10 Essentials\" Gear Checklist",
"Zapier Expert - \"Lead to CRM\" Zap JSON Export",
"Watercolor Artist - Paper Texture Background Pack",
"Scrum Master - Retrospective Meeting Agenda Template",
"Resume Writer - ATS-Friendly Resume Word Template",
"System Admin - PowerShell Script for User Creation",
"Mom Blogger - \"Kids' Chore Chart\" Printable",
"Crypto Trader - Portfolio Rebalancing Spreadsheet",
"Beekeeper - Hive Inspection Log PDF",
"Video Editor - Sound Effects Pack (Transitions)",
"Stylist - \"Capsule Wardrobe\" Planner PDF",
"Career Coach - Salary Negotiation Email Scripts",
"WordPress Developer - `functions.php` Snippet Collection",
"Occupational Therapist - Sensory Diet Activity List",
"Dungeon Master - NPC Generator Table (D&D 5e)",
"Solar Consultant - Solar Panel ROI Calculator",
"Handyman - Home Maintenance Schedule (Yearly)",
"YouTube Creator - Video Description Boilerplate Text",
"Google Sheets Expert - Custom Script for Auto-Sorting",
"Podcast Editor - Audition/GarageBand Keyboard Shortcuts PDF",
"Art Teacher - \"Color Theory\" Lesson Plan",
"Flight Sim Enthusiast - Custom Cockpit Control Profile",
"Bookkeeper - Monthly Expense Categorization Guide",
"Supply Chain Manager - Vendor Evaluation Scorecard",
"Coffee Roaster - Roast Profile Log Sheet",
"Arduino Hobbyist - Sensor Library Code Snippets",
"Public Speaker - Keynote Slide Deck Template",
"House Flipper - Renovation Budget Estimator",
"Call Center Manager - Quality Assurance Evaluation Form",
"Academic Researcher - Literature Review Matrix (Excel)",
"Mix Engineer - Mastering Chain Preset (Logic Pro)",
"Pattern Designer - Seamless Fabric Patterns (TIFF)",
"Pet Sitter - \"While You Were Away\" Report Card",
"Affiliate Marketer - Link Tracking Spreadsheet",
"Machine Learning Engineer - Dataset Cleaning Python Notebook",
"Drama Teacher - Monologue Selection for Teens",
"Cartographer - Fantasy Map Brush Set for Photoshop",
"Mortgage Broker - Loan Amortization Schedule Excel",
"Online Course Creator - Course Outline Template",
"Compliance Officer - GDPR Compliance Checklist",
"Streetwear Brand Owner - T-Shirt Mockup PSD",
"Notion User - \"Habit Tracker\" Minimalist Template",
"College Student - \"Finals Week\" Study Schedule",
"Electrician - Circuit Breaker Label Template",
"Sommelier - Wine Tasting Note Sheet",
"Frontend Dev - CSS Grid Layout Cheatsheet",
"Ghostwriter - Non-Fiction Book Proposal Template",
"Event Coordinator - Seating Chart Layout Tool (Visio/PDF)",
"Influencer - Lightbox Preset for Instagram Stories",
"Warehouse Manager - Safety Inspection Checklist",
"Golfer - Handicap Tracking Spreadsheet",
"Logic Pro User - Keyboard Shortcut Sticker Sheet (Printable)",
"Airbnb Superhost - \"Local Recommendations\" Map Guide",
"Survivalist - Bug Out Bag Inventory List"
];

export async function selectTopic() {
    console.log("Selecting random topic from list...");
    
    // Logic: Select Random Topic
    const randomIndex = Math.floor(Math.random() * topicsList.length);
    const selectedTopic = topicsList[randomIndex];

    return selectedTopic;
}
